name: Update Profiles on Windows

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 ? * WED,SAT"

jobs:
  update-profiles:
    runs-on: windows-2022
    permissions:
      contents: write  # 关键权限设置

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # 获取完整历史记录

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          architecture: x64

      - name: Install dependencies
        run: pip3 install beautifulsoup4

      - name: Run main script
        run: pwsh ./run.ps1

      - name: Check for changes
        id: check_changes
        run: |
          git status --porcelain
          if (git status --porcelain) {
            echo "has_changes=true" >> $env:GITHUB_OUTPUT
          } else {
            echo "has_changes=false" >> $env:GITHUB_OUTPUT
          }

      - name: Commit changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          Set-TimeZone -Id "China Standard Time"
          $china_date = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
          $message = "更新（代理配置）: `${china_date}` 更新。"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "$message"

      - name: Push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
